platform :ios, '7.0'

# Add Application pods here

target :unit_tests, :exclusive => true do
  link_with 'UnitTests'
  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
  pod 'Expecta'
  pod 'OCMockito'
  pod 'Swizzlean'
  pod 'OHHTTPStubs'
end
